name: irescue_manuscript
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::gawk=5.0.1
  - conda-forge::python=3.9.2
  - bioconda::bedtools=2.30.0
  - bioconda::samtools=1.12
  - bioconda::star=2.7.9a
  - bioconda::irescue=1.0.2
